node {
   def commit_id ="v1.0"
   env.DOCKER_HOST = 'npipe:////./pipe/dockerDesktopLinuxEngine'  //
   stage('Preparation') {
     checkout scm
     //batchfile("git rev-parse --short HEAD > commit-id")                        
     //commit_id = readFile('.git/commit-id').trim()
     //commit_id = batchfile(git rev-parse HEAD) //windows specific command replacement for sh

   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       bat 'npm install --include=dev'         //windows specific command replacement for sh. The include=dev is a recent change in npm
       bat 'npm test'
     }
   }
   
      stage('docker build/push') {
     docker.withRegistry('https://index.docker.io/v2/', 'dockerhub') {                //added dockerhub credentials in jenkins
       def app = docker.build("mmgriffi/docker-nodejs-demo:${commit_id}", '.').push()
     }
   }

}

