node {
   def commit_id
   stage('Preparation') {
     checkout scm
     batchfile("git rev-parse --short HEAD > commit-id"                        
     //commit_id = readFile('.git/commit-id').trim()
     //commit_id = batchfile(git rev-parse HEAD) //windows specific command replacement for sh
     //commit_id = "9867ad4"
     def commit_id = "V1.0"

   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       batchfile('npm install --only=dev')         //windows specific command replacement for sh
       batchfile('npm test')
     }
   }
   stage('docker build/push') {
     docker.withRegistry('https://index.docker.io/v2/', 'dockerhub') {
       def app = docker.build("mmgriffi/docker-nodejs-demo:${commit_id}", '.').push()
     }
   }
}
