node {
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       batchfile('npm install --only=dev')         //windows specific command replacement for sh
       batchfile('npm test')
     }
   }
   stage('docker build/push') {
     docker.withRegistry('https://index.docker.io/v2/', 'dockerhub') {
       def app = docker.build("mmgriffi/docker-nodejs-demo:${commit_id}", '.').push()
     }
   }
}
